//
//  Guides.swift
//  Habito
//
//  Created by Kenneth Yang on 2/12/25.
//

import Foundation

let guides = [
    GuideModel(title: "Which Side Should You Sleep On?", description: Descriptions.sleepingWoman.rawValue, img: "sleepingWoman"),
    GuideModel(title: "Why Should You Run?", description: Descriptions.runningWoman.rawValue, img: "womanRunning"),
    GuideModel(title: "Expert Tips on How to Cycle Up Hills Properly", description: Descriptions.biking.rawValue, img:"bikingWoman")
]

enum Descriptions: String {
    case sleepingWoman = "If you toss and turn, you may be looking for a comfortable sleep position. There may be benefits to sleeping on your side, but does it matter which side? \nSome research suggests that sleeping on one side may be better for certain reasons. But it s more important to focus on getting enough rest, rather than your position.If you toss and turn, you may be looking for a comfortable sleep position. There may be benefits to sleeping on your side, but does it matter which side? \nSome research suggests that sleeping on one side may be better for certain reasons. But it s more important to focus on getting enough rest, rather than your position.If you toss and turn, you may be looking for a comfortable sleep position. There may be benefits to sleeping on your side, but does it matter which side? \nSome research suggests that sleeping on one side may be better for certain reasons. But it s more important to focus on getting enough rest, rather than your position.If you toss and turn, you may be looking for a comfortable sleep position. There may be benefits to sleeping on your side, but does it matter which side? \nSome research suggests that sleeping on one side may be better for certain reasons. But it s more important to focus on getting enough rest, rather than your position."
    
    case runningWoman = "Marathoners are the thoroughbreds of high-performance runners, but even the draft horses of the running world — slow and steady joggers — improve their health. A study out this week in the Journal of the American College of Cardiology finds that even five to 10 minutes a day of low-intensity running is enough to extend life by several years, compared with not running at all. It shows that the minimal healthy  of exercise is smaller than many people might assume. Marathoners are the thoroughbreds of high-performance runners, but even the draft horses of the running world — slow and steady joggers — improve their health. A study out this week in the Journal of the American College of Cardiology finds that even five to 10 minutes a day of low-intensity running is enough to extend life by several years, compared with not running at all. It shows that the minimal healthy  of exercise is smaller than many people might assume. Marathoners are the thoroughbreds of high-performance runners, but even the draft horses of the running world — slow and steady joggers — improve their health. A study out this week in the Journal of the American College of Cardiology finds that even five to 10 minutes a day of low-intensity running is enough to extend life by several years, compared with not running at all. It shows that the minimal healthy  of exercise is smaller than many people might assume."
    
    case biking = "Simon Warren has been cycling up hills on a bicycle for a long time at this point. The English cyclist authored his first book on leg-shaking inclines - The 100 Greatest Cycling Climbs - back in 2010. Since that first road cyclist’s guide to the British hills, he’s since released a full 14 more guides in similar vein, covering everything from the best hill climbs in almost every region of Britain to the best hill climbs in Belgium, Spain, Italy, on the Tour de France and beyond. Warren's journey on the bike started a long time before that first book, of course. Once you realise you can beat your friends up the hills, you want to find more hills to beat your friends up...Simon Warren has been cycling up hills on a bicycle for a long time at this point. The English cyclist authored his first book on leg-shaking inclines - The 100 Greatest Cycling Climbs - back in 2010. Since that first road cyclist’s guide to the British hills, he’s since released a full 14 more guides in similar vein, covering everything from the best hill climbs in almost every region of Britain to the best hill climbs in Belgium, Spain, Italy, on the Tour de France and beyond. Warren's journey on the bike started a long time before that first book, of course. Once you realise you can beat your friends up the hills, you want to find more hills to beat your friends up...Simon Warren has been cycling up hills on a bicycle for a long time at this point. The English cyclist authored his first book on leg-shaking inclines - The 100 Greatest Cycling Climbs - back in 2010. Since that first road cyclist’s guide to the British hills, he’s since released a full 14 more guides in similar vein, covering everything from the best hill climbs in almost every region of Britain to the best hill climbs in Belgium, Spain, Italy, on the Tour de France and beyond. Warren's journey on the bike started a long time before that first book, of course. Once you realise you can beat your friends up the hills, you want to find more hills to beat your friends up..."
    
    
}
