//
//  Guides.swift
//  Habito
//
//  Created by Kenneth Yang on 2/12/25.
//

import Foundation

let guides = [
    GuideModel(title: "Which Side Should You Sleep On?", description: Descriptions.sleepingWoman.rawValue, img: "sleepingWoman"),
    GuideModel(title: "Why Should You Run?", description: Descriptions.runningWoman.rawValue, img: "womanRunning"),
    GuideModel(title: "Expert Tips on How to Cycle Up Hills Properly", description: Descriptions.biking.rawValue, img:"bikingWoman")
]

enum Descriptions: String {
    case sleepingWoman = "If you toss and turn, you may be looking for a comfortable sleep position. There may be benefits to sleeping on your side, but does it matter which side? \nSome research suggests that sleeping on one side may be better for certain reasons. But it s more important to focus on getting enough rest, rather than your position.If you toss and turn, you may be looking for a comfortable sleep position. There may be benefits to sleeping on your side, but does it matter which side? \nPeople tend to snore more when sleeping on their backs instead of their sides. When you sleep on your back, it is easier for your tongue to fall back into your throat, creating an obstruction that can result in snoring. When you sleep on your side, your airway may stay more open, so you can breathe easier. For this reason, physicians recommend people with position-dependant sleep apnea, a serious sleep-related breathing disorder, sleep on their side to help relieve symptoms. \nYour brain gets rid of waste throughout the day and night, but it does the majority of this important work at night while you sleep. Researchers analyzed whether your sleep position affects your brain’s efficiency in waste removal, and the side sleeping position allows for faster waste removal than either the stomach or back sleeping positions."
    
    case runningWoman = "Marathoners are the thoroughbreds of high-performance runners, but even the draft horses of the running world — slow and steady joggers — improve their health. A study out this week in the Journal of the American College of Cardiology finds that even five to 10 minutes a day of low-intensity running is enough to extend life by several years, compared with not running at all. It shows that the minimal healthy  of exercise is smaller than many people might assume. The new study focused on a group of more than 55,000 men and women ages 18 to 100. About a quarter of them were runners. Over 15 years, those who ran just 50 minutes a week or fewer at a moderate pace were less likely to die from either cardiovascular disease or any cause, compared with those who didn't run at all. Although running can trim away some of your existing risk of cardiovascular disease, it doesn't entirely eliminate it. The combined effect of lifestyle, diet, and family history still contribute to your lifetime risk. This study used preventing death to measure the benefit of running, but it's not the most typical reason for running. \"Many dedicated long-term runners do not run because they want to live longer,\" Dr. Baggish notes. \"They run because it makes them feel better on a daily basis. There is a mood elevating, quality-of-life benefit that comes from being a regular exerciser.\""
    
    case biking = "Simon Warren has been cycling up hills on a bicycle for a long time at this point. The English cyclist authored his first book on leg-shaking inclines - The 100 Greatest Cycling Climbs - back in 2010. Since that first road cyclist’s guide to the British hills, he’s since released a full 14 more guides in similar vein, covering everything from the best hill climbs in almost every region of Britain to the best hill climbs in Belgium, Spain, Italy, on the Tour de France and beyond. “I always rode a bike growing up in the 70s,” Simon told me. “Then I saved up my £6 a week babysitting money and bought a racing bike. I didn’t have any ideas of actually racing it, but my uncle was a cyclist and he sort of bullied me into it! He said ‘you’ve got a racing bike, so we’re going racing’. He took me to a time trial on the A1 - it was a little safer back then in the late 80s, but you had articulated lorries and whatever going by - and I just fell head over heels for it.“ Later that year there was a club hill climb championship and I was the first junior and got a trophy. So whenever we went on cycling trips, I’d just make sure I was first up the hills - and that was when I found my calling. I started entering events and I wasn’t winning, but I was incredibly skinny, I had a good power to weight ratio, and I had enough athletic ability to keep me going.Obviously, you're going to want to eat well before a big bike ride, but also while you're actually on the climb - especially if it's a long one. It's personal preference what you consume. Some opt for energy gels, drinks or bars, taken in appropriate portions. Others prefer dates or bananas. Or heck, munch a big potato or two as you ride the climb. Not quite as convenient, though, is it?"
    
    
}
